### ISSUE TITLE
Error: invalid signature: 0x6064b50

### ISSUE THREAD

**Issue by xinzai2014** [EvanOxfeld/node-unzip#110]
Error: invalid signature: 0x6064b50
at /home/jwcloud/node_modules/unzip/lib/parse.js:58:13
at runCallback (timers.js:781:20)
at tryOnImmediate (timers.js:743:5)
at processImmediate [as _immediateCallback] (timers.js:714:5)

the file‘s size is 4.8GB

**Comment by 16slowly** [comment]
+1

**Comment by mhr3** [comment]
That's signature of a zip64 file, this library doesn't support those. You should try [yauzl](https://github.com/thejoshwolfe/yauzl) or [unzip-stream](https://github.com/mhr3/unzip-stream).
