### ISSUE TITLE
Please remove dependency on 'natives

### ISSUE THREAD

**Issue by MikhailArkhipov** [EvanOxfeld/node-unzip#115]
See 
https://www.npmjs.com/package/natives
https://github.com/Microsoft/vscode/issues/47569

"This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x."

**Comment by ZJONSSON** [comment]
Thanks @MikhailArkhipov, I did not find any references to `natives` in the dependency tree of `unzipper`.  I do see `graceful-fs@4.1.11` as one of the dependencies.   

For reference: `unzipper` is an actively managed fork of `unzip` with full backwards compatibility and advanced features (such as streaming unzip from url and quickly unzipping single files using the end directory) - please let me know if I can help you further with this or if you have any other concerns.

**Comment by MikhailArkhipov** [comment]
```
-- unzip@0.1.11
  -- fstream@0.1.31
    -- graceful-fs@3.0.11
      -- natives@1.1.1
```

**Comment by ZJONSSON** [comment]
To clarify, my comment was regarding the actively managed fork which is published as `unzipper` not `unzip`.  
https://www.npmjs.com/package/unzipper
`npm install unzipper`

**Comment by blake-regalia** [comment]
If `unzip` is no longer managed, please contact the owners to ask them consider deprecating it as it is causing major headaches for the node.js community when upgrading to v10.x.
```
$ npm owner ls unzip
evanoxfeld <eoxfeld@gmail.com>
joeferner <joe@fernsroth.com>
```

**Comment by package71** [comment]
* **Version**: 12.0.0
```
fs.js:27
const { Math, Object, Reflect } = primordials;
                                  ^

ReferenceError: primordials is not defined
    at fs.js:27:35
    at req_ (/Users/bdev/Documents/Projects/exchanger-api/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/bdev/Documents/Projects/exchanger-api/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/bdev/Documents/Projects/exchanger-api/node_modules/unzip/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/bdev/Documents/Projects/exchanger-api/node_modules/unzip/node_modules/graceful-fs/graceful-fs.js:3:27)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/bdev/Documents/Projects/exchanger-api/node_modules/unzip/node_modules/fstream/lib/reader.js:4:10)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
```
