### ISSUE TITLE
some issue about unzip

### ISSUE THREAD

**Issue by greengerong** [EvanOxfeld/node-unzip#27]
There are some issue , when i unzip a zip file(inlcude two docx file) on mac os.
error like :
events.js:71
        throw arguments[1]; // Unhandled 'error' event
                       ^
TypeError: Invalid non-string/buffer chunk
    at chunkInvalid (/Users/twer/project/opensource/vital-signs/node_modules/unzip/node_modules/readable-stream/lib/_stream_readable.js:341:10)
    at readableAddChunk (/Users/twer/project/opensource/vital-signs/node_modules/unzip/node_modules/readable-stream/lib/_stream_readable.js:128:12)
    at Match.Readable.push (/Users/twer/project/opensource/vital-signs/node_modules/unzip/node_modules/readable-stream/lib/_stream_readable.js:115:10)
    at Match.Transform.push (/Users/twer/project/opensource/vital-signs/node_modules/unzip/node_modules/readable-stream/lib/_stream_transform.js:141:32)
    at Match._matchFn (/Users/twer/project/opensource/vital-signs/node_modules/unzip/lib/parse.js:161:31)
    at Match._transform (/Users/twer/project/opensource/vital-signs/node_modules/unzip/node_modules/match-stream/match.js:39:10)
    at Match.Transform._read (/Users/twer/project/opensource/vital-signs/node_modules/unzip/node_modules/readable-stream/lib/_stream_transform.js:180:10)
    at Match.Transform._write (/Users/twer/project/opensource/vital-signs/node_modules/unzip/node_modules/readable-stream/lib/_stream_transform.js:168:12)
    at doWrite (/Users/twer/project/opensource/vital-signs/node_modules/unzip/node_modules/readable-stream/lib/_stream_writable.js:211:10)
    at writeOrBuffer (/Users/twer/project/opensource/vital-signs/node_modules/unzip/node_modules/readable-stream/lib/_stream_writable.js:201:5)
    at Match.Writable.write (/Users/twer/project/opensource/vital-signs/node_modules/unzip/node_modules/readable-stream/lib/_stream_writable.js:172:11)
    at write (/Users/twer/project/opensource/vital-signs/node_modules/unzip/node_modules/readable-stream/lib/_stream_readable.js:550:24)
    at flow (/Users/twer/project/opensource/vital-signs/node_modules/unzip/node_modules/readable-stream/lib/_stream_readable.js:559:7)
    at Readable.pipe (/Users/twer/project/opensource/vital-signs/node_modules/unzip/node_modules/readable-stream/lib/_stream_readable.js:527:7)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)

**Comment by greengerong** [comment]
no response
