### ISSUE TITLE
"invalid signature: 0x47d68d75" error on zip files from TeamCity

### ISSUE THREAD

**Issue by evil-shrike** [EvanOxfeld/node-unzip#41]
JetBrains TeamCity can pack artifacts as zip files. I'm trying to unzip a file from my build artifacts with `unzip`. It's failing with error : 

```
Error: invalid signature: 0x47d68d75
    at path\to\unzip\unzip\lib\parse.js:63:13
    at process._tickCallback (node.js:415:13)
```

BTW "bower install" fails on such zip-files as it uses `unzip`.

The Zip file itself is OK. It can be unpacked with WinRAR and official PKZIP from PKWARE without any errors.

When I created new zip files with WinRAR and PKWARE's PKZIP `unzip` fails on them in another way:

```
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.

RangeError: Maximum call stack size exceeded
```

What format of ZIP the module does support? It seems to be incompatible with official PKZIP.

**Comment by cscott** [comment]
It seems to be that 'stored' files in the zip are not supported.

**Comment by amio** [comment]
Same as #32

**Comment by seagullua** [comment]
This is fixed in new package https://www.npmjs.com/package/unzip2

**Comment by brandonscript** [comment]
It would be great if you could unpublish the old unzip package from NPM or at least add a note saying it's superseded by unzip2.
