### ISSUE TITLE
invalid signature fatal error

### ISSUE THREAD

**Issue by missinglink** [EvanOxfeld/node-unzip#52]
``` bash
Error: invalid signature: 0xcb633d21
    at /var/www/xxx/unzip/lib/parse.js:63:13
    at process._tickCallback (node.js:415:13)
```

**Comment by missinglink** [comment]
The issue here is that when an error occurs; an `'error'` event is emitted on the stream. This causes the upstream socket to `unpipe` and disconnect; essentially halting the whole stream.

**Comment by seagullua** [comment]
This is fixed in new package https://www.npmjs.com/package/unzip2
